# Generated by Django 3.0.8 on 2020-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_donorprofile_patientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='city',
            field=models.CharField(default='New Delhi', max_length=50),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(default='New Delhi', max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
