# Generated by Django 3.0.8 on 2020-08-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0005_auto_20200829_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='lat',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lng',
            field=models.CharField(default='', max_length=10),
        ),
    ]
