# Generated by Django 3.0.8 on 2020-08-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0006_auto_20200831_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(default='', max_length=15),
        ),
    ]
