# Generated by Django 3.0.8 on 2020-08-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0007_userprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dob',
            field=models.CharField(default='', max_length=15),
        ),
    ]
