# Generated by Django 3.0.8 on 2020-09-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0009_auto_20200901_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='lungs',
            new_name='lung',
        ),
    ]
