# Generated by Django 3.0.8 on 2020-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0010_auto_20200901_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='dob',
            field=models.CharField(default='', max_length=15),
        ),
    ]
