# Generated by Django 3.0.8 on 2020-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0011_donorprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='lng',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='lng',
            field=models.CharField(default='', max_length=20),
        ),
    ]
