# Generated by Django 3.0.8 on 2020-09-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0013_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
