# Generated by Django 3.0.8 on 2020-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0014_auto_20200903_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='message',
        ),
    ]
